"""Structured JSON logging: observational only, quiet by default.

ADR-0007. A log line has to be tied back to a reproducible evaluation, so records
carry ``model_version``, ``config_hash``, ``input_hash``, and ``window_profile``
where available, and a :class:`GreenMachineError` is written as **fields** rather
than a formatted sentence.

Two constraints shape everything here:

* **Observational only.** Nothing in this module mutates a domain object, alters
  an exception, changes a return value, catches an application failure, derives
  an identifier, or reads the project clock. Logging can never move a grade.
* **Quiet by default.** Importing GreenMachine emits nothing, and configuring a
  logger without a stream emits nothing. Output happens only when a caller
  explicitly supplies one.

The root logger is never touched, no handler is installed at import time, and no
timestamp is generated by this module — ``logging`` records its own timing
internally, and the formatter simply does not read it, so two records of the
same event are byte-identical.
"""

from __future__ import annotations

import json
import logging
from collections.abc import MutableMapping
from dataclasses import dataclass, fields
from typing import Any, TextIO

from .errors import GreenMachineError

__all__ = [
    "CONTEXT_ATTRIBUTE",
    "DEFAULT_LEVEL",
    "ERROR_ATTRIBUTE",
    "LogContext",
    "StructuredJsonFormatter",
    "bind_context",
    "configure_logger",
]

# Quiet by default: warnings and worse. Never read from the environment.
DEFAULT_LEVEL = logging.WARNING

# Record attributes the formatter looks for. Namespaced so they cannot collide
# with the stdlib's own LogRecord fields.
CONTEXT_ATTRIBUTE = "greenmachine_context"
ERROR_ATTRIBUTE = "greenmachine_error"


@dataclass(frozen=True, slots=True)
class LogContext:
    """Immutable correlation fields tying a log line to an evaluation.

    Plain strings rather than domain types: ``common`` must not import
    ``domain``, so a caller passes ``window_profile.value``. Every field is
    optional — an early log line may know only the model version.
    """

    model_version: str | None = None
    config_hash: str | None = None
    input_hash: str | None = None
    window_profile: str | None = None

    def __post_init__(self) -> None:
        for spec in fields(self):
            value = getattr(self, spec.name)
            if value is not None and not isinstance(value, str):
                raise TypeError(
                    f"LogContext.{spec.name} must be a string or None, got {type(value).__name__}"
                )

    def as_dict(self) -> dict[str, str]:
        """A newly allocated dictionary of the fields that were set.

        Absent fields are consistently **omitted** rather than emitted as nulls,
        so a record's key set always reflects what was actually known.
        """
        return {
            spec.name: getattr(self, spec.name)
            for spec in fields(self)
            if getattr(self, spec.name) is not None
        }


class StructuredJsonFormatter(logging.Formatter):
    """Render a record as a single deterministic JSON object.

    Field names are fixed, keys are sorted, and separators are compact, so
    records are stable and machine-readable. There is deliberately no
    ``default=`` hook: an unserializable value must fail loudly rather than be
    silently turned into its ``repr``.

    No timestamp is emitted — this module generates none, and the record's own
    timing metadata is not read.
    """

    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, Any] = {
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }

        context = getattr(record, CONTEXT_ATTRIBUTE, None)
        if isinstance(context, LogContext):
            payload.update(context.as_dict())

        error = self._resolve_error(record)
        if error is not None:
            payload["error"] = error.as_log_record()

        return json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )

    @staticmethod
    def _resolve_error(record: logging.LogRecord) -> GreenMachineError | None:
        """Find a GreenMachineError on the record, without altering it."""
        attached = getattr(record, ERROR_ATTRIBUTE, None)
        if isinstance(attached, GreenMachineError):
            return attached
        if record.exc_info is not None:
            candidate = record.exc_info[1]
            if isinstance(candidate, GreenMachineError):
                return candidate
        return None


def configure_logger(
    name: str,
    *,
    stream: TextIO | None = None,
    level: int = DEFAULT_LEVEL,
) -> logging.Logger:
    """Configure and return one named logger. Never touches the root logger.

    With no ``stream`` the logger gets a :class:`logging.NullHandler` and emits
    nothing: that is the default path, and it stays silent. Passing a stream
    attaches a :class:`StructuredJsonFormatter` to it.

    Existing handlers on the named logger are removed first, so calling this
    twice leaves one handler and one copy of each message rather than two.
    ``propagate`` is disabled so records never reach the root logger, which is
    both how duplicate output is avoided and why no global state is mutated.

    Args:
        name: A non-empty logger name. The root logger cannot be configured.
        stream: Where JSON records go. ``None`` means silence.
        level: Threshold for this logger. Explicit; never read from the
            environment.
    """
    if not isinstance(name, str):
        raise TypeError(f"logger name must be a string, got {type(name).__name__}")
    if not name.strip():
        raise ValueError("logger name must not be blank; the root logger is not configurable")
    # Split rather than combined with `or`: a bool *is* an int, so the two
    # checks are genuinely different questions and one is not statically dead.
    if isinstance(level, bool):
        raise TypeError("level must be an int logging level, not a bool")
    if not isinstance(level, int):
        raise TypeError(f"level must be an int, got {type(level).__name__}")

    logger = logging.getLogger(name)

    for existing in list(logger.handlers):
        logger.removeHandler(existing)

    handler: logging.Handler
    if stream is None:
        handler = logging.NullHandler()
    else:
        handler = logging.StreamHandler(stream)
        handler.setFormatter(StructuredJsonFormatter())

    handler.setLevel(level)
    logger.addHandler(handler)
    logger.setLevel(level)
    logger.propagate = False
    return logger


class _ContextAdapter(logging.LoggerAdapter[logging.Logger]):
    """Attaches a :class:`LogContext` to every record without mutating anything."""

    def __init__(self, logger: logging.Logger, context: LogContext) -> None:
        super().__init__(logger, {})
        self.context = context

    def process(
        self, msg: Any, kwargs: MutableMapping[str, Any]
    ) -> tuple[Any, MutableMapping[str, Any]]:
        """Return new mappings; the caller's ``kwargs`` and ``extra`` are untouched.

        A per-call ``extra`` wins over the bound context, so a caller can
        override a correlation field for one line without rebinding.
        """
        supplied = kwargs.get("extra")
        extra: dict[str, Any] = dict(supplied) if supplied else {}
        extra.setdefault(CONTEXT_ATTRIBUTE, self.context)

        updated: dict[str, Any] = dict(kwargs)
        updated["extra"] = extra
        return msg, updated


def bind_context(
    logger: logging.Logger, context: LogContext
) -> logging.LoggerAdapter[logging.Logger]:
    """Bind correlation fields to a logger, returning an adapter.

    The adapter carries the context onto each record it emits. Neither the
    logger nor the context is modified.
    """
    if not isinstance(logger, logging.Logger):
        raise TypeError(f"logger must be a logging.Logger, got {type(logger).__name__}")
    if not isinstance(context, LogContext):
        raise TypeError(f"context must be a LogContext, got {type(context).__name__}")
    return _ContextAdapter(logger, context)
