"""The §GMF-004 parks screen: pure view logic over the ``InputSnapshot``.

No streamlit import, like every other package under ``src`` — the composition
root owns the widgets and this package owns everything handed to them.
"""

from greenmachine.parks.view import (
    ABSENCE_WORDS,
    ALL_COLUMNS,
    FACTOR_COLUMNS,
    FORECAST_COLUMN,
    LHB_FACTOR_COLUMN,
    RHB_FACTOR_COLUMN,
    ROOF_COLUMN,
    ROOF_STATUS_WORDS,
    TEAM_COLUMN,
    VENUE_COLUMN,
    VENUE_TYPE_COLUMN,
    VENUE_TYPE_WORDS,
    ForecastDisposition,
    ParksScreen,
    factor_absence_notes,
    factor_detail_notes,
    forecast_disposition,
    forecast_suppression_notes,
    forecast_text,
    forecast_value_text,
    ordered_parks,
    park_factor_fields,
    roof_text,
    screen_frames,
    screen_rows,
    screen_state_frame,
    unavailable_forecast_notes,
    venue_type_text,
)

__all__ = [
    "ABSENCE_WORDS",
    "ALL_COLUMNS",
    "FACTOR_COLUMNS",
    "FORECAST_COLUMN",
    "LHB_FACTOR_COLUMN",
    "RHB_FACTOR_COLUMN",
    "ROOF_COLUMN",
    "ROOF_STATUS_WORDS",
    "TEAM_COLUMN",
    "VENUE_COLUMN",
    "VENUE_TYPE_COLUMN",
    "VENUE_TYPE_WORDS",
    "ForecastDisposition",
    "ParksScreen",
    "factor_absence_notes",
    "factor_detail_notes",
    "forecast_disposition",
    "forecast_suppression_notes",
    "forecast_text",
    "forecast_value_text",
    "ordered_parks",
    "park_factor_fields",
    "roof_text",
    "screen_frames",
    "screen_rows",
    "screen_state_frame",
    "unavailable_forecast_notes",
    "venue_type_text",
]
